DemoCRUD/Controllers/StateDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoCRUD.Models;
using System.Data.Entity;

namespace DemoCRUD.Controllers
{
    public class StateDetailsController : Controller
    {
        WorldEntities db = new WorldEntities();
        // GET: StateDetails
        public ActionResult Index()
        {
            //WorldEntities db = new WorldEntities();
            List<StateViewModeel> StatListModel = (from c in db.StateTable
                                 join
                                    d in db.Country on c.CountryId equals d.CountryId
                                 select new { c, d }).ToList().Select(x=>new StateViewModeel {
                                     CountyryId = x.c.CountryId,
                                     CountryName =x.d.CountryName,
                                     StateId=x.c.StateId,
                                     StateName=x.c.StatName
                                 }).ToList();
            return View(StatListModel);
        }
        public ActionResult StateInsert()
        {
            
            var context = db.Country.Select(x => new SelectListItem { Text = x.CountryName,Value=x.CountryId.ToString()}).ToList();
            List<SelectListItem> list = new List<SelectListItem>().ToList();
            ViewBag.countryList = context;
            return View();
        }
        [HttpPost]
        public ActionResult StateInsert(StateTable model)
        {
         
            if (ModelState.IsValid)
            {
                db.StateTable.Add(model);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Index");
            }
            return View();
            
        }
        public ActionResult EditInsert(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorldEntities db = new WorldEntities();
            StateTable state = db.StateTable.Find(id);
            if (state == null)
            {
                return HttpNotFound();
            }
            //return View();
            var context = db.Country.Select(x => new SelectListItem { Text = x.CountryName, Value = x.CountryId.ToString() }).ToList();
            List<SelectListItem> list = new List<SelectListItem>().ToList();
            ViewBag.countryList = context;
            return View(state);
        }
        [HttpPost]
        public ActionResult EditInsert(StateTable model)
        {
            StateTable table = db.StateTable.Find(model.StateId);
            if(table!=null)
            {
                if (ModelState.IsValid)
                {
                    table.StatName = model.StatName;
                    db.Entry(table).State = EntityState.Modified;
                    db.SaveChanges();
                    ModelState.Clear();
                    return RedirectToAction("Index");
                }
            }
            return View();

        }
        public ActionResult StateDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //WorldEntities db = new WorldEntities();
            StateTable state = db.StateTable.Find(id);
            if (db == null)
            {
                return HttpNotFound();
            }
            return View(state);
        }
        [HttpPost, ActionName("StateDelete")]
        public ActionResult StateDeleteConfirmed(int id)
        {
            //WorldEntities db = new WorldEntities();
            StateTable table = db.StateTable.Find(id);
            db.StateTable.Remove(table);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
      

    }

}

DemoCRUD/Views/StateDetails/EditInsert.cshtml
@model DemoCRUD.StateTable
@{
    ViewBag.Title = "EditInsert";
}

<h2>EditState</h2>

@using (Html.BeginForm("EditInsert", "StateDetails", FormMethod.Post))
{

<div class="form-horizontal">
    <hr />
    @Html.HiddenFor(x => x.StateId)
    <div>
        @Html.Label("Country")
        <div>
            @Html.DropDownListFor(x => x.CountryId, new SelectList(ViewBag.countryList, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div>
        @Html.LabelFor(x => x.StatName)
        <div>
            @Html.EditorFor(x => x.StatName)
        </div>
    </div>
    <br />
    <div>
        <div>
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
    <br />
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemoCRUD/Views/StateDetails/Index.cshtml
@model IEnumerable<DemoCRUD.Models.StateViewModeel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "StateDetails", FormMethod.Get))
{
    <div> @Html.ActionLink("Add New", "StateInsert")<br /></div>
    <hr />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Country")
            </th>
            <th>@Html.DisplayName("State")</th>
            <th></th>
            <th>@Html.DisplayName("Action")</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.CountryName
                </td>
                <td>
                    @item.StateName
                </td>
                <td></td>
                <td>
                    @Html.ActionLink("Edit", "EditInsert", "StateDetails", new { id = item.StateId }, htmlAttributes: new { @class = "btn btn-warning btn-large" }) ||
                    @Html.ActionLink("Delete", "StateDelete", "StateDetails", new { id = item.StateId }, htmlAttributes: new { @class = "btn btn-danger btn-large" })

                </td>
            </tr>
        }
    </table>
}

DemoCRUD/Views/StateDetails/StateDelete.cshtml
@model DemoCRUD.StateTable
@{
    ViewBag.Title = "StateDelete";
}

<h2>StateDelete</h2>
<br />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>State</h4>
    <hr />

    @*@using (Html.BeginForm("StateDelete", "StateDetails", FormMethod.Get))
    {
        <table class="table-bordered">
            <tr>
                <th> @Html.DisplayNameFor(model => model.StatName)</th>
                <th></th>
            </tr>
            <tr></tr>
            <tr>
                <td>@Html.DisplayFor(model => model.StatName)</td>
                <td></td>
            </tr>

        </table>
    }*@
    @using (Html.BeginForm("StateDelete", "StateDetails", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.StateId)
        <div>
            <br />
            <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(model => model.StatName)</dt>
            <dd>@Html.DisplayFor(model => model.StatName)</dd>
           
            </dl>
            <div class="form-group">
                
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>


    }
</div>

DemoCRUD/Views/StateDetails/StateInsert.cshtml
@model DemoCRUD.StateTable
@{
    ViewBag.Title = "StateInsert";
}

<h2>States</h2>

@using (Html.BeginForm("StateInsert", "StateDetails", FormMethod.Post))
{

<div class="form-horizontal">
    <hr />
    <div>
        @Html.Label("Country Name")
        <div>
            @Html.DropDownListFor(x => x.CountryId, new SelectList(ViewBag.countryList, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div>
        @Html.LabelFor(x=>x.StatName)
        <div>
            @Html.EditorFor(x=>x.StatName)
        </div>
    </div>
    <br />
    <div>
        <div>
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
    <br />
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>