DemoCRUD/Controllers/CountryDetailController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Net;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoCRUD;
using DemoCRUD.Models;


namespace DemoCRUD.Controllers
{
    public class CountryDetailController : Controller
    {
        // GET: CountryDetail
        
        public ActionResult Index()
        {
            WorldEntities db = new WorldEntities();
            return View(db.Country.ToList());
        }
        public ActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Insert(Country model)
        {
            WorldEntities db = new WorldEntities();
                if (ModelState.IsValid)
                {
                    db.Country.Add(model);
                    db.SaveChanges();
                    
                }
                return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorldEntities db = new WorldEntities();
            Country country = db.Country.Find(id);
            if (db == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }
        [HttpPost]
        public ActionResult Edit(Country model)
        {
            WorldEntities db = new WorldEntities();
            Country country = db.Country.Find(model.CountryId);
            if (country != null)
            {
                if (ModelState.IsValid)
                {
                    country.CountryName = model.CountryName;
                    db.Entry(country).State = EntityState.Modified;
                    db.SaveChanges();

                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorldEntities db = new WorldEntities();
            Country country = db.Country.Find(id);
            if (db == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }
        [HttpPost,ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            WorldEntities db = new WorldEntities();
            Country country = db.Country.Find(id);
            db.Country.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DemoCRUD/Views/CountryDetail/Delete.cshtml
@model DemoCRUD.Country

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    @using (Html.BeginForm("Delete", "CountryDetail", FormMethod.Get))
    {
        <table class="table-bordered">
            <tr>
                <th> @Html.DisplayNameFor(model => model.CountryName)</th>
                <th></th>
            </tr>
           <tr></tr>
            <tr>
                <td>@Html.DisplayFor(model => model.CountryName)</td>
                <td></td>
            </tr>

        </table>
    }
    @using (Html.BeginForm("Delete", "CountryDetail", FormMethod.Post))
    {
        <div><br />
            <div>
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>


    }
</div>

DemoCRUD/Views/CountryDetail/Edit.cshtml
@model DemoCRUD.Country

@{
    ViewBag.Title = "EditCountry";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","CountryDetail",FormMethod.Post))
{
    
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.HiddenFor(x=>x.CountryId)
        <div>
            @Html.LabelFor(x => x.CountryName)
            <div>
                @Html.EditorFor(x => x.CountryName)
            </div>
        </div>
        <br />
        <div>
            <div>
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemoCRUD/Views/CountryDetail/Index.cshtml
@model IEnumerable<DemoCRUD.Country>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "CountryDetail", FormMethod.Get))
{
<div> @Html.ActionLink("Add New Country", "Insert")<br /></div>
    <br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Country")
        </th>
        <th></th>
        <th>@Html.DisplayName("Action")</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
               @* @Html.Display(item.CountryName)*@
                @item.CountryName
            </td>
            <td></td>
            <td>
                @Html.ActionLink("Edit", "Edit", "CountryDetail", new { id = item.CountryId }, htmlAttributes: new { @class = "btn btn-warning btn-large" }) || 
                @Html.ActionLink("Delete", "Delete", "CountryDetail", new { id = item.CountryId }, htmlAttributes: new { @class = "btn btn-danger btn-large" })

            </td>
        </tr>
    }
</table>
}

DemoCRUD/Views/CountryDetail/Insert.cshtml
@model DemoCRUD.Country
@{
    ViewBag.Title = "Add Country";
}

<h2>Insert</h2>
@using (Html.BeginForm("Insert", "CountryDetail", FormMethod.Post))
{
   
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        <div>
            @Html.LabelFor(x => x.CountryName)
            <div>
                @Html.EditorFor(x => x.CountryName)
            </div>
        </div>
        <br />
        <div>
            <div>
                <input type="submit" value="Save" class="btn btn-Success" />
            </div>
        </div>
    </div>
    <br />
}
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>